/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  31337: {
    AgentReceiptRegistry: {
      address: "0x4A65b9d13908487A1654be48e6aa9Bc701735910",
      abi: [
        {
          inputs: [],
          name: "InactiveOffer",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidId",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidReceipt",
          type: "error",
        },
        {
          inputs: [],
          name: "NotProvider",
          type: "error",
        },
        {
          inputs: [],
          name: "OfferExists",
          type: "error",
        },
        {
          inputs: [],
          name: "OfferMissing",
          type: "error",
        },
        {
          inputs: [],
          name: "ReceiptExists",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "offerId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "provider",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint96",
              name: "priceTinybar",
              type: "uint96",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "metadataDigest",
              type: "bytes32",
            },
          ],
          name: "OfferRegistered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "offerId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "active",
              type: "bool",
            },
          ],
          name: "OfferStatusChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "receiptId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "offerId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "artifactDigest",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "hcsMessageDigest",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "hcsSequence",
              type: "uint64",
            },
          ],
          name: "ReceiptAnchored",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "receiptId",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "offerId",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "artifactDigest",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "hcsMessageDigest",
              type: "bytes32",
            },
            {
              internalType: "uint64",
              name: "hcsSequence",
              type: "uint64",
            },
          ],
          name: "anchorReceipt",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          name: "offers",
          outputs: [
            {
              internalType: "address",
              name: "provider",
              type: "address",
            },
            {
              internalType: "uint96",
              name: "priceTinybar",
              type: "uint96",
            },
            {
              internalType: "bytes32",
              name: "metadataDigest",
              type: "bytes32",
            },
            {
              internalType: "bool",
              name: "active",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          name: "receipts",
          outputs: [
            {
              internalType: "bytes32",
              name: "offerId",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "artifactDigest",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "hcsMessageDigest",
              type: "bytes32",
            },
            {
              internalType: "uint64",
              name: "hcsSequence",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "createdAt",
              type: "uint64",
            },
            {
              internalType: "address",
              name: "provider",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "offerId",
              type: "bytes32",
            },
            {
              internalType: "uint96",
              name: "priceTinybar",
              type: "uint96",
            },
            {
              internalType: "bytes32",
              name: "metadataDigest",
              type: "bytes32",
            },
          ],
          name: "registerOffer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "offerId",
              type: "bytes32",
            },
            {
              internalType: "bool",
              name: "active",
              type: "bool",
            },
          ],
          name: "setOfferActive",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 41030258,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
